### PR TITLE
[1.18] feat: add luckperms integration with meta

### PR DESCRIPTION
**Pull request by Yann151924**
Add support for luckperms metadata.

I use the same approach as you with ftbranks but i did it with luckperms.

### CODE REVIEW

**Comment by Yann151924** [comment]
When the server reboot or the player is killed, there is a bug with luckperms. I have the problem on my atm7 server. The problem come when the loggedOut method is called. The luckperms api is not enable, kinda weird.

**Comment by Yann151924** [comment]
I made a workaround with a try-catch that's fix the problem the crash until luckperms investigate more on their hand.

**Comment by wolflord212312** [comment]
Hmm assuming this merge wont happen? And even if it does would not be updated to 1.19 would it  Just wondering as it has been open for over 8 months

**Comment by Yann151924** [comment]
Nearly the same pr has been merged in 1.18 & 1.19, so maybe the dev forget to see this one.

@desht since you accept the one in ftb-essentials can you accept it here ? :)

**Comment by desht** [comment]
I'll take a look.

**Comment by desht** [comment]
Closing this PR; see https://github.com/FTBTeam/FTB-Chunks/commit/c37086c08cf319ad8a632a633c72e9c6273ee400

**Comment by Yann151924** [comment]
👍 i was hesitating to put something like you in case for futur implementation.

If you could backport it to 1.18 it will be great, some modpack still running the 1.18 forge version

**Pull request closed without merging**
