### PR TITLE
Allowing the use of rocket in claimed chunks if the user is wearing an elytra (trying to fly). Fixes #114

### LINKED ISSUE #114: Players can't use rockets for elytra flight
In someone else's claimed chunk a player can't use rockets.

### PR DESCRIPTION
**Pull request by savvasdalkitsis**

### CODE REVIEW

**Comment by savvasdalkitsis** [comment]
Fixes #114

**Comment by LatvianModder** [comment]
I won't accept this PR because I was gonna do it in a different way - blacklist item tag so that there is no need for many different edge cases like buckets etc

**Comment by savvasdalkitsis** [comment]
No worries. Good to know this is being worked on :D

**Comment by savvasdalkitsis** [comment]
Perhaps going for a whitelist instead of a blacklist is a better option? That way items added by mods will not be allowed by default. Many mods add weapons and other griefing items

**Pull request closed without merging**
