### PR TITLE
Fixes #375

### PR DESCRIPTION
**Pull request by vladislemon**
Fixes https://github.com/FTBTeam/FTB-Mods-Issues/issues/375

I'm not sure my solution is correct, waiting for review.

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
A note for the future, please don't reformat code, I know it's likely your IDE that did the compression to a `.*` import so just a heads up if you make any future PR's. I'll review this PR in the coming days :+1:

**Comment by MaxNeedsSnacks** [comment]
> A note for the future, please don't reformat code, I know it's likely your IDE that did the compression to a `.*` import so just a heads up if you make any future PR's. I'll review this PR in the coming days +1

We should probably look into making an .editorconfig file or something for the mod repos, shouldn't we :P

**Comment by vladislemon** [comment]
> A note for the future, please don't reformat code, I know it's likely your IDE that did the compression to a `.*` import so just a heads up if you make any future PR's. I'll review this PR in the coming days +1

Fixed that.

**Comment by desht** [comment]
This PR needs to be raised against the 1.18/dev branch, not 1.18/main.  (Merging into 1.18/main will kick off CI to publish a new build to Curseforge, which isn't desirable here)

**Comment by vladislemon** [comment]
New PR: https://github.com/FTBTeam/FTB-Chunks/pull/229

**Pull request closed without merging**
